project:
  type: website
  output-dir: docs

website:
  title: "FOR 128"
  image: assets/stat20-hex.png
  site-url: "https://www.for128.org/"
  navbar:
    title: false
    logo: assets/for128-hex.png
    logo-alt: "FOR 128 logo"
    background: white
    foreground: "gray-800"
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - text: Slides
        menu:
          - slides/test_slides.qmd
      - href: assignments.qmd
        text: Assignments
      - href: https://www.finley-lab.com/files/ifdar/
        target: "_blank"
        rel: "noopener noreferrer"
        text: Textbook

format:
  html:
    theme: sandstone
    css: assets/styles.scss
    toc: true
    
resources: 
  - CNAME

editor: visual

