project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!labs/lab_01.qmd"
    - "!labs/lab_02.qmd"
    - "!labs/lab_04.qmd"
    - "!labs/lab_05.qmd"
    - "!labs/lab_06.qmd"
    - "!labs/lab_07.qmd"
    - "!labs/lab_08.qmd"
    - "!labs/lab_09.qmd"
    - "!labs/lab_10.qmd"
    - "!labs/lab_11.qmd"
    - "!quizzes/"
    - "!labs/datasets/"
    - "!/in_class/*.qmd"
    - "!midterms/"

website:
  title: "FOR 128"
  image: assets/stat20-hex.png
  site-url: "https://www.for128.org/"
  favicon: assets/favicon.ico
  navbar:
    title: false
    logo: assets/for128-hex.png
    logo-alt: "FOR 128 logo"
    background: white
    foreground: "gray-800"
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - text: Slides (Weeks 1 - 5)
        menu:
          - href: slides/w1d1.qmd
            text: "Week 1 Day 1"
          - href: slides/w1d2.qmd
            text: "Week 1 Day 2"
          - href: slides/w2d1.qmd
            text: "Week 2 Day 1"
          - href: slides/w2d2.qmd
            text: "Week 2 Day 2"
          - href: slides/w3d1.qmd
            text: "Week 3 Day 1"
          - href: slides/w4d1.qmd
            text: "Week 4 Day 1 (Notes)"
          - href: slides/w4d2.qmd
            text: "Week 4 Day 2"
          - href: slides/w5d1.qmd
            text: "Week 5 Day 1"
          - href: slides/w5d2.qmd
            text: "Week 5 Day 2"
      - text: Slides (Weeks 6+)
        menu:
          - href: slides/w6d1.qmd
            text: "Week 6 Day 1"
          - href: slides/w7d1.qmd
            text: "Week 7 Day 1"
          - href: slides/w7d2.qmd
            text: "Week 7 Day 2"
          - href: slides/w8d1.qmd
            text: "Week 8 Day 1"
          - href: slides/w8d2.qmd
            text: "Week 8 Day 2"
          - href: slides/w9d1.qmd
            text: "Week 9 Day 1"
          - href: slides/w10d1.qmd
            text: "Week 10 Day 1"
          - href: slides/w10d2.qmd
            text: "Week 10 Day 2"
          - href: slides/w11d1.qmd
            text: "Week 11 Day 1"
          - href: slides/w11d2.qmd
            text: "Week 11 Day 2"
          - href: slides/w12d1.qmd
            text: "Week 12 Day 1"
          - href: slides/w12d2.qmd
            text: "Week 12 Day 2"
          - href: slides/w13d1.qmd
            text: "Week 13 Day 1"
          - href: slides/w14d1.qmd
            text: "Week 14 Day 1"
      - href: assignments.qmd
        text: Assignments
      - href: posts.qmd
        text: Class Blog
      - href: final_project.qmd
        text: Final Project
      - href: recordings.qmd
        text: Lecture Recordings
      - href: https://www.finley-lab.com/files/ifdar/
        target: "_blank"
        rel: "noopener noreferrer"
        text: Textbook

format:
  html:
    theme: sandstone
    css: assets/styles.scss
    toc: true

resources: 
  - CNAME

editor: visual

