---
title: "a nice title"
subtitle: "FOR 128: Lab 2"
author: "Insert Your Name Here"
date: "9/5/2024"
format:
  pdf: default
editor: 
  mode: source
---

## Welcome

Welcome to Lab 2! Today, we'll start importing and exporting data in R, thinking about relative and absolute paths, and navigating our computer. Let's get started!

### Learning objectives

-   Understand your computer's file system.
-   Be able to read data from a specific location.
-   Be able to write data to a specific location.
-   Understand and use relative and absolute paths.

### Deliverables (i.e., what to put in the lab drop box)

Upload your rendered PDF (`lab_02.pdf`) **and** Quarto (`lab_02.qmd`) document to the lab drop box. Make sure the Quarto document properly renders to PDF.

### Collaborator(s)

List any collaborators you worked with below. 






# Part 1: Conceptual Questions

## Exercise 1

Do Exercise 3.1 from IFDAR.

(a)

(b)

(c)

(d)

(e)

(f)


## Exercise 2

Do Exercise 3.2 from IFDAR.

(a)

(b)

(c)

(d)


# Part 2: Application with R

## Exercise 3



# Wrap up

Congratulations! You've made it to the end of Lab 1. Make sure to render your final document and submit both the .pdf and .qmd file to D2L.
